[2023-11-29T22:00:25.863+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T19:58:52.282171+00:00 [queued]>
[2023-11-29T22:00:25.867+0200] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lviv_weather.inject_data manual__2023-11-29T19:58:52.282171+00:00 [queued]>
[2023-11-29T22:00:25.868+0200] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-29T22:00:25.880+0200] {taskinstance.py:1382} INFO - Executing <Task(SqliteOperator): inject_data> on 2023-11-29 19:58:52.282171+00:00
[2023-11-29T22:00:25.882+0200] {standard_task_runner.py:57} INFO - Started process 100070 to run task
[2023-11-29T22:00:25.885+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'lviv_weather', 'inject_data', 'manual__2023-11-29T19:58:52.282171+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/lviv_weather.py', '--cfg-path', '/tmp/tmpaclrozag']
[2023-11-29T22:00:25.886+0200] {standard_task_runner.py:85} INFO - Job 34: Subtask inject_data
[2023-11-29T22:00:25.914+0200] {task_command.py:416} INFO - Running <TaskInstance: lviv_weather.inject_data manual__2023-11-29T19:58:52.282171+00:00 [running]> on host yurabd.
[2023-11-29T22:00:25.956+0200] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'inject_data', field 'sql'. Template: "\n            INSERT INTO measures (timestamp, temp) VALUES\n            ({{ti.xcom_pull(task_ids='process_data')[0]}},\n            {{ti.xcom_pull(task_ids='process_data')[1]}},\n            {{ti.xcom_pull(task_ids='process_data')[2]}});\n            "
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-11-29T22:00:25.969+0200] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/mnt/f/UCU/BatchProc/lab1/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-11-29T22:00:25.989+0200] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=lviv_weather, task_id=inject_data, execution_date=20231129T195852, start_date=20231129T200025, end_date=20231129T200025
[2023-11-29T22:00:25.998+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task inject_data (None has no element 0; 100070)
[2023-11-29T22:00:26.017+0200] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-29T22:00:26.024+0200] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
